import discord

default_role_perms_comp_raid = discord.PermissionOverwrite(create_instant_invite=False,
                                                           manage_channels=False,
                                                           manage_roles=False,
                                                           manage_webhooks=False,
                                                           manage_messages=False,
                                                           embed_links=False,
                                                           attach_files=False,
                                                           mention_everyone=False,
                                                           external_emojis=False,
                                                           add_reactions=False,
                                                           send_messages=False,
                                                           send_tts_messages=False,
                                                           read_messages=True,
                                                           read_message_history=True)

bot_perms = discord.PermissionOverwrite(create_instant_invite=False,
                                        manage_channels=True,
                                        manage_roles=True,
                                        manage_webhooks=True,
                                        manage_messages=True,
                                        embed_links=True,
                                        attach_files=True,
                                        mention_everyone=False,
                                        external_emojis=True,
                                        add_reactions=True,
                                        send_messages=True,
                                        send_tts_messages=False,
                                        read_messages=True,
                                        read_message_history=True)

default_role_perms_commands = discord.PermissionOverwrite(create_instant_invite=False,
                                                          manage_channels=False,
                                                          manage_roles=False,
                                                          manage_webhooks=False,
                                                          manage_messages=False,
                                                          embed_links=True,
                                                          attach_files=True,
                                                          mention_everyone=True,
                                                          external_emojis=True,
                                                          add_reactions=True,
                                                          send_messages=True,
                                                          send_tts_messages=False,
                                                          read_messages=True,
                                                          read_message_history=True)

bot_join_permissions = [('add_reactions', True),
                        ('administrator', True),
                        ('attach_files', True),
                        ('ban_members', True),
                        ('change_nickname', True),
                        ('connect', True),
                        ('create_instant_invite', True),
                        ('deafen_members', True),
                        ('embed_links', True),
                        ('external_emojis', True),
                        ('kick_members', True),
                        ('manage_channels', True),
                        ('manage_emojis', True),
                        ('manage_guild', True),
                        ('manage_messages', True),
                        ('manage_nicknames', True),
                        ('manage_roles', True),
                        ('manage_webhooks', True),
                        ('mention_everyone', True),
                        ('move_members', True),
                        ('mute_members', True),
                        ('priority_speaker', True),
                        ('read_message_history', True),
                        ('read_messages', True),
                        ('send_messages', True),
                        ('send_tts_messages', True),
                        ('speak', True),
                        ('stream', True),
                        ('use_voice_activation', True),
                        ('view_audit_log', True)]
